### ISSUE TITLE
import error: process is not defined

### ISSUE THREAD

**Issue by hakanertug** [Schum123/svelte-loading-spinners#1]
Hi,
```javascript
import { Jumper } from 'svelte-loading-spinners'
```

i add import code to my page i get this error on console.

![image](https://user-images.githubusercontent.com/2025574/80848808-405d0680-8c1d-11ea-8afe-688ece617128.png)

How can i solve this problem?
thanks.

**Comment by Schum123** [comment]
Hello @hakanertug,

I'm not sure why that is happening. 

try to add [@rollup/plugin-replace](https://github.com/rollup/rollup-plugin-replace)

and in your `rollup.config.js` add,

```
import replace from '@rollup/plugin-replace';

plugins: [
    replace({
      "process.env.NODE_ENV": process.env.NODE_ENV,
    }),
    svelte({
      ...
    })
]
```

**Comment by hakanertug** [comment]
woww!
Thank's it's work...

**Comment by quantuminformation** [comment]
I get the same error, I am not wanting to change my rollup config as it shouldn't be necessary

**Comment by bennsamuel** [comment]
I also get the same error.

**Comment by raulviitor1** [comment]
I'm getting the same error

**Comment by quantuminformation** [comment]
The problem is the word `process` is replaced everywhere in the source.

**Comment by quantuminformation** [comment]
see https://github.com/rollup/rollup/issues/3650#issuecomment-652787487

**Comment by Schum123** [comment]
With latest version i hope this is not an issue anymore with emotion removed as dependency.
