### ISSUE TITLE
Is NPM Package working?

### ISSUE THREAD

**Issue by telkamp** [Schum123/svelte-loading-spinners#10]
Does anyone use the package "svelte-loading-spinners": 0.1.1 from https://www.npmjs.com/package/svelte-loading-spinners?
It seems not to work. Even if it is published 3 month ago, some of the newer components are not included in the package (e.g. Moon, Square)

The example available in this repository includes the components directly from source code, not from the npm package. BTW, the bundle files are committed to the repository here. But when I build the example again, it tells me that the components Moon & Square are not defined...

**Comment by Schum123** [comment]
Hi @telkamp,

They work fine for me. 

See this repl, https://svelte.dev/repl/c283160b21ed4d8fbc36baf70cdc52a5?version=3.29.4
