### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by rjkz808** [Schum123/svelte-loading-spinners#11]
Good library! Would be great if it has some type definitions. Here's an [example](https://github.com/hperrin/svelte-material-ui/issues/163#issuecomment-706657579) of how people added those for svelte-material-ui.

By the way, it's also a good idea to make this library TypeScript first. It can be achieved by changing rollup config and adding some simple types to the code:

```ts
export let size: number = 60;
export let color: string = "#FF3E00";
export let unit: string = "px";
```

**Comment by Schum123** [comment]
@rjkz808 Thank you. Typescript support added.
