### ISSUE TITLE
Jumper problem with safari 

### ISSUE THREAD

**Issue by amirjani** [Schum123/svelte-loading-spinners#12]
Hi,

there is a problem in loading Jumper component in safari, when I remove border-radius It'll appear, but with border-radius, It won't work on safari, but other browsers work fine

**Comment by Schum123** [comment]
Will look into this when i have more time :)

**Comment by Schum123** [comment]
@amirjani This should be solved with version 0.1.2. Will update demo page as soon as i can :)

**Comment by amirjani** [comment]
> @amirjani This should be solved with version 0.1.2. Will update demo page as soon as i can :)

Thanks
