### ISSUE TITLE
Diamonds-spinner seems broken

### ISSUE THREAD

**Issue by jis3r** [Schum123/svelte-loading-spinners#19]
First of all thank you very much for this nice collection of spinners, saved a lot of work for me! :)

I just tried different spinners in my project, and the diamonds-spinner seems to be broken: it is just one pulsing diamond visible. I tried to inspect the spinner and it seems like all three diamonds are pulsing on the same spot, resulting in the horizontal motion not being visible. That's just my guess, so this might not be the reason.

https://user-images.githubusercontent.com/72663107/122412172-a291db80-cf85-11eb-858a-e9cc5970922f.mp4

**Comment by Schum123** [comment]
Hello @jis3r! Thank you very much for the kind words.

I will look into this. Seems to be broken for me aswell.

**Comment by Schum123** [comment]
@jis3r This should be fixed now.

[REPL](https://svelte.dev/repl/c283160b21ed4d8fbc36baf70cdc52a5?version=3.29.4)
