### ISSUE TITLE
issue with circle2 and size

### ISSUE THREAD

**Issue by quantuminformation** [Schum123/svelte-loading-spinners#4]
I tried

`<Circle2 size="35" color="#FF3E00" unit="px" />`

result

![image](https://user-images.githubusercontent.com/216566/82303523-5871ab80-99bb-11ea-8355-834647557f6d.png)

removing size:

![image](https://user-images.githubusercontent.com/216566/82303583-6aebe500-99bb-11ea-8aa2-d50f5d6c1613.png)

Also the color attr deosn't change anything

**Comment by Schum123** [comment]
@quantuminformation  Thanks for notice. This should be fixed now. I added more props for Circle2,  `colorOuter`, `colorCenter`, `colorInner`.

**Comment by quantuminformation** [comment]
thx
