### ISSUE TITLE
Failed to resolve import "./Circle.svelte"

### ISSUE THREAD

**Issue by xelfer** [Schum123/svelte-loading-spinners#43]
I `npm i --save-dev svelte-loading-spinners`

then I put this in <script> in my Main.svelte:
`
import { Jumper } from 'svelte-loading-spinners/'`

and I get this error: 
<img width="830" alt="image" src="https://user-images.githubusercontent.com/1923936/195972791-aa32d524-59a5-4aa8-8206-d9faf2484864.png">

am i doing something wrong?

**Comment by Schum123** [comment]
Hello @xelfer 
Try with the latest version (0.3.2). Made changes to use SvelteKit instead.

**Comment by xelfer** [comment]
Thanks @Schum123, looks like it's working now. Appreciate it!
