### ISSUE TITLE
It seems that the publish format is incorrect in v0.3.5

### ISSUE THREAD

**Issue by jill64** [Schum123/svelte-loading-spinners#54]
The following error occurs in v0.3.5.

![screenshot 2024-04-03 103028 png](https://github.com/Schum123/svelte-loading-spinners/assets/143883742/60bbae1e-366d-4244-91e4-3b0d065d3d18)

It appears that the toolchain for this library is out of date and the package needs to be published using the following procedure.

```sh
npm run build && cd package && npm publish
```

**Comment by AdamOlsson** [comment]
I am also experiencing the above issue.

**Comment by Schum123** [comment]
@jill64 @AdamOlsson A new version was just published.

**Comment by AdamOlsson** [comment]
I've verified and it works :)
